version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: postgres_postgis
    restart: always
    environment:
      POSTGRES_DB: geoproduction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: flask_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: geoproduction_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./backend/ObservationData_agriculture.csv:/app/ObservationData_agriculture.csv
      - ./backend/ObservationData_elevage.csv:/app/ObservationData_elevage.csv
      - ./backend/ObservationData_peche.csv:/app/ObservationData_peche.csv

volumes:
  postgres_data:
    driver: bridge
